In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
#data collection 

import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import pandas as pd

data = gutenberg.raw('shakespeare-hamlet.txt')

with open('hamlet.txt','w') as file:
    file.write(data)

print("File 'hamlet.txt' created successfully.")

File 'hamlet.txt' created successfully.


[nltk_data] Downloading package gutenberg to /usr/share/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [4]:
## data preprocessing

import numpy as np

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

with open('hamlet.txt','r') as file:
    text=file.read().lower()
tokenizer=Tokenizer()
tokenizer.fit_on_texts([text])
total_words=len(tokenizer.word_index)+1
total_words

4818

In [5]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'i': 5,
 'you': 6,
 'a': 7,
 'my': 8,
 'it': 9,
 'in': 10,
 'that': 11,
 'ham': 12,
 'is': 13,
 'not': 14,
 'his': 15,
 'this': 16,
 'with': 17,
 'your': 18,
 'but': 19,
 'for': 20,
 'me': 21,
 'lord': 22,
 'as': 23,
 'what': 24,
 'he': 25,
 'be': 26,
 'so': 27,
 'him': 28,
 'haue': 29,
 'king': 30,
 'will': 31,
 'no': 32,
 'our': 33,
 'we': 34,
 'on': 35,
 'are': 36,
 'if': 37,
 'all': 38,
 'then': 39,
 'shall': 40,
 'by': 41,
 'thou': 42,
 'come': 43,
 'or': 44,
 'hamlet': 45,
 'good': 46,
 'do': 47,
 'hor': 48,
 'her': 49,
 'let': 50,
 'now': 51,
 'thy': 52,
 'how': 53,
 'more': 54,
 'they': 55,
 'from': 56,
 'enter': 57,
 'at': 58,
 'was': 59,
 'oh': 60,
 'like': 61,
 'most': 62,
 'there': 63,
 'well': 64,
 'know': 65,
 'selfe': 66,
 'would': 67,
 'them': 68,
 'loue': 69,
 'may': 70,
 "'tis": 71,
 'vs': 72,
 'sir': 73,
 'qu': 74,
 'which': 75,
 'did': 76,
 'why': 77,
 'laer': 78,
 'giue': 79,
 'thee': 80,
 'ile': 81,
 'must': 82,
 'hath': 

In [8]:
#create an input sequence

inputsequences=[]

for line in text.split('\n'):
    token_list=tokenizer.texts_to_sequences([line])[0]

    for i in range(1,len(token_list)):
        n_gram_sequence=token_list[:i+1]

        inputsequences.append(n_gram_sequence)

In [9]:
inputsequences


[[1, 687],
 [1, 687, 4],
 [1, 687, 4, 45],
 [1, 687, 4, 45, 41],
 [1, 687, 4, 45, 41, 1886],
 [1, 687, 4, 45, 41, 1886, 1887],
 [1, 687, 4, 45, 41, 1886, 1887, 1888],
 [1180, 1889],
 [1180, 1889, 1890],
 [1180, 1889, 1890, 1891],
 [57, 407],
 [57, 407, 2],
 [57, 407, 2, 1181],
 [57, 407, 2, 1181, 177],
 [57, 407, 2, 1181, 177, 1892],
 [407, 1182],
 [407, 1182, 63],
 [408, 162],
 [408, 162, 377],
 [408, 162, 377, 21],
 [408, 162, 377, 21, 247],
 [408, 162, 377, 21, 247, 882],
 [18, 66],
 [451, 224],
 [451, 224, 248],
 [451, 224, 248, 1],
 [451, 224, 248, 1, 30],
 [408, 407],
 [451, 25],
 [408, 6],
 [408, 6, 43],
 [408, 6, 43, 62],
 [408, 6, 43, 62, 1893],
 [408, 6, 43, 62, 1893, 96],
 [408, 6, 43, 62, 1893, 96, 18],
 [408, 6, 43, 62, 1893, 96, 18, 566],
 [451, 71],
 [451, 71, 51],
 [451, 71, 51, 1894],
 [451, 71, 51, 1894, 567],
 [451, 71, 51, 1894, 567, 378],
 [451, 71, 51, 1894, 567, 378, 80],
 [451, 71, 51, 1894, 567, 378, 80, 3],
 [451, 71, 51, 1894, 567, 378, 80, 3, 273],
 [451, 71

In [10]:
##pad sequences

max_sequences_len=max([len(x) for x in inputsequences])
max_sequences_len

14

In [12]:
inputsequences=np.array(pad_sequences(inputsequences,maxlen=max_sequences_len, padding='pre'))

In [13]:
inputsequences

array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193]], dtype=int32)

In [17]:
# create predicotors and labels

import tensorflow as tf
x,y = inputsequences[:,:-1],inputsequences[:,-1]

In [18]:
x

array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       ...,
       [   0,    0,    0, ...,  687,    4,   45],
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4]], dtype=int32)

In [19]:
y

array([ 687,    4,   45, ..., 1047,    4,  193], dtype=int32)

In [20]:
y=tf.keras.utils.to_categorical(y,num_classes=total_words
                               )

In [21]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [22]:
#train and test

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [30]:
#train our lstm RNN

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM, Dense, Dropout

#define model

model=Sequential()
model.add(Embedding(total_words,100, input_length=max_sequences_len))
model.add(LSTM(150, return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation="softmax"))

model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=['accuracy'])

model.summary()



Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:
#trian model

history=model.fit(x_train,y_train, epochs=50, validation_data=(x_test,y_test), verbose=1)

Epoch 1/50


I0000 00:00:1777232834.787336    1741 cuda_dnn.cc:529] Loaded cuDNN version 91002


644/644 ━━━━━━━━━━━━━━━━━━━━ 12s 9ms/step - accuracy: 0.0312 - loss: 7.1391 - val_accuracy: 0.0334 - val_loss: 6.7515
Epoch 2/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.0374 - loss: 6.4369 - val_accuracy: 0.0408 - val_loss: 6.8215
Epoch 3/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.0427 - loss: 6.2866 - val_accuracy: 0.0478 - val_loss: 6.9016
Epoch 4/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.0503 - loss: 6.1501 - val_accuracy: 0.0482 - val_loss: 6.8839
Epoch 5/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.0519 - loss: 6.0662 - val_accuracy: 0.0509 - val_loss: 6.9382
Epoch 6/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.0589 - loss: 5.9091 - val_accuracy: 0.0556 - val_loss: 6.9738
Epoch 7/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.0693 - loss: 5.7465 - val_accuracy: 0.0620 - val_loss: 7.0280
Epoch 8/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.0764 - loss: 5.6547 - val_accuracy: 0.0612 - val

In [39]:
#  predict next word

def predict_next_word(model, tokenizer, text, max_sequence_len):
    token_list=tokenizer.texts_to_sequences([text])[0]

    if len(token_list) >= max_sequence_len:
        token_list=token_list[-(max_sequences_len-1):]
    token_list=pad_sequences([token_list],maxlen=max_sequence_len-1, padding='pre')
    predicted=model.predict(token_list,verbose=0)

    predicted_word_index=np.argmax(predicted,axis=1)
    for word, index in tokenizer.word_index.items():
        if index==predicted_word_index:
            return word
    return None

In [40]:
input_text="to be or not to be "

print (f"Input text:{input_text}")
max_sequences_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text, max_sequences_len)
print(f"next word predicted:{next_word}")

Input text:to be or not to be 
next word predicted:buried


In [43]:
import pickle
model.save("next_word_lstm.h5")

with open("tokenizer.pickle","wb") as file :
    pickle.dump(tokenizer,file, protocol=pickle.HIGHEST_PROTOCOL)

In [44]:
input_text="to be better than "

print (f"Input text:{input_text}")
max_sequences_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text, max_sequences_len)
print(f"next word predicted:{next_word}")

Input text:to be better than 
next word predicted:true


In [45]:
input_text="i love you"

print (f"Input text:{input_text}")
max_sequences_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text, max_sequences_len)
print(f"next word predicted:{next_word}")

Input text:i love you
next word predicted:not


In [46]:

history=model.fit(x_train,y_train, epochs=100, validation_data=(x_test,y_test), verbose=1)

Epoch 1/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.4730 - loss: 2.4128 - val_accuracy: 0.0478 - val_loss: 11.4970
Epoch 2/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.4656 - loss: 2.4228 - val_accuracy: 0.0497 - val_loss: 11.5745
Epoch 3/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.4822 - loss: 2.3605 - val_accuracy: 0.0507 - val_loss: 11.6039
Epoch 4/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.4867 - loss: 2.3320 - val_accuracy: 0.0488 - val_loss: 11.7459
Epoch 5/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.4892 - loss: 2.3311 - val_accuracy: 0.0517 - val_loss: 11.7663
Epoch 6/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.5013 - loss: 2.2705 - val_accuracy: 0.0493 - val_loss: 11.8069
Epoch 7/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.4872 - loss: 2.2998 - val_accuracy: 0.0490 - val_loss: 11.8794
Epoch 8/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.5059 - loss: 2.2268 - v

In [48]:
import pickle
model.save("new_next_word_lstm.h5")

with open("new_tokenizer.pickle","wb") as file :
    pickle.dump(tokenizer,file, protocol=pickle.HIGHEST_PROTOCOL)